language: python

# for container-y googdness:
sudo: false

addons:
  postgresql: "9.2"

python:
  - "3.4"
  - "2.7"

# command to install dependencies
install: "pip install -Ue .[test,build]"

before_script:
- sh -c "psql -c 'create database testdb' -U postgres"
- sh -c 'psql -d testdb -c "CREATE EXTENSION btree_gist;" -U postgres'
- psql --version

# command to run tests, e.g. python setup.py test
script: DB_URL=postgres://postgres@localhost/testdb nosetests --with-cov --cov=mortar_mixins

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: RAgcCDH/F3zIMBaENqcWlk1Y9npIMVjHgCxY2qL7C1qRCgzyAfoHI+pIOvnHqVRXG1Cz4+MaYTo+B4Iec5HxUF9gjWl9XOtrNVUCzmaCCCyrLq24esQ2IJ5r5y2jJCt/nOQdh9OFTWr0IxPzYhOrm4/HZwP4IZ+WmnNnWhWs7TT/mClzuCOd6tp1YgCnahp5ea2T2hY3zrBiCUtCtpY31kCXoane/7jx69xzdNMmCjjt95BZLYLL0Ync3K4dDi0aDb9/2Ca/gRXx1KPycv9cymkE9Z4DjdKCY/EklciiObJfIibRxvV22gVJPfKWIVnmtHchr0yo+EloQK0bhVKUGnLlHOMk2sJlpk9Ak4e0+gJegWae9bugqxpeif8HAa6J5DmK+EkfauzG5TK7UuKEkb6LTV+vP6wPpdex7abjfxv0VbXjVMblBa8XdYjfMHYFM8g90G7Y+6rZPAEGshRqnXhO+ccvskyCnOKkTihHdQd/m7M93aQJDVwv8zi0KSQXal6UsjkYtnqiflRzIPtGjLlVYxrpZdLUo7Hv5LP6LVnzgPYvbJMkwevypDrhVXuTlTiy9F+Rh9qqyaIAcpOkZInVytanJ+OMme/7jHaWzhq5OlFvGUCE61ArG/ctRyWSafp+bUrhyFfi6rieu2ByMaLsYdw7ncxybU7sf522WUA=
  on:
    tags: true
    repo: Mortar/mortar_mixins
    python: "3.4"
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
